# version: '3.8'
# services:
#   # airflow:
#   #   build:
#   #     context: ./docker/inference
#   #     dockerfile: Dockerfile
#   #   ports:
#   #     - "8080:8080"
#   #   volumes:
#   #     - ./dags:/app/dags
#   #     - ./data:/app/data
#   #     - ./mlruns:/app/mlruns
#   #     - ./mlflow.db:/app/mlflow.db
#   #   environment:
#   #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#   #     - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////app/airflow.db
#   #   depends_on:
#   #     - mlflow
#   mlflow:
#     build:
#       context: ./docker/mlflow
#       dockerfile: Dockerfile
#     ports:
#       - "9000:9000"
#     volumes:
#       - ./mlruns:/app/mlruns
#       - ./mlflow.db:/app/mlflow.db


services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data

  mlflow-server:
    build:
      context: ./docker/mlflow
      dockerfile: Dockerfile
    container_name: mlflow-server
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow
    depends_on:
      - minio

  iris-train:
    build:
      context: ./src/training
      dockerfile: Dockerfile
    container_name: iris-train
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    depends_on:
      - mlflow-server
      - minio

  iris-api:
    build:
      context: ./src/inference
      dockerfile: Dockerfile
    container_name: iris-api
    ports:
      - "8000:5000"
    depends_on:
      - iris-train